#ifndef ID3V1TAGSDEF_H
#define ID3V1TAGSDEF_H
#include<string>
using namespace std;
const unsigned int GENRECOUNT=148;
//流派信息
const string Genre[GENRECOUNT]={"Blues",
                   "Classic Rock",
                   "Country",
                   "Dance",
                   "Disco",
                   "Funk",
                   "Grunge",
                   "Hip-Hop",
                   "Jazz",
                   "Metal",
                   "New Age",
                   "Oldies",
                   "Other",
                   "Pop",
                   "R&B",
                   "Rap",
                   "Reggae",
                   "Rock",
                   "Techno",
                   "Industrial",
                   "Alternative",
                   "Ska",
                   "Death Metal",
                   "Pranks",
                   "Soundtrack",
                   "Euro-Techno",
                   "Ambient",
                   "Trip-Hop",
                   "Vocal",
                   "Jazz+Funk",
                   "Fusion",
                   "Trance",
                   "Classical",
                   "Instrumental",
                   "Acid",
                   "House",
                   "Game",
                   "Sound Clip",
                   "Gospel",
                   "Noise",
                   "Alternative Rock",
                   "Bass",
                   "Soul",
                   "Punk",
                   "Space",
                   "Meditative",
                   "Instrumental Pop",
                   "Instrumental Rock",
                   "Ethnic",
                   "Gothic",
                   "Darkwave",
                   "Techno-Industrial",
                   "Electronic",
                   "Pop-Folk",
                   "Eurodance",
                   "Dream",
                   "Southern Rock",
                   "Comedy",
                   "Cult",
                   "Gangsta",
                   "Top 40",
                   "Christian Rap",
                   "Pop/Funk",
                   "Jungle",
                   "Native US",
                   "Cabaret",
                   "New Wave",
                   "Psychadelic",
                   "Rave",
                   "Showtunes",
                   "Trailer",
                   "Lo-Fi",
                   "Tribal",
                   "Acid Punk",
                   "Acid Jazz",
                   "Polka",
                   "Retro",
                   "Musical",
                   "Rock & Roll",
                   "Hard Rock",
                   "Folk",
                   "Folk-Rock",
                   "National Folk",
                   "Swing",
                   "Fast Fusion",
                   "Bebop",
                   "Latin",
                   "Revival",
                   "Celtic",
                   "Bluegrass",
                   "Avantgarde",
                   "Gothic Rock",
                   "Progressive Rock",
                   "Psychedelic Rock",
                   "Symphonic Rock",
                   "Slow Rock",
                   "Big Band",
                   "Chorus",
                   "Easy Listening",
                   "Acoustic",
                   "Humour",
                   "Speech",
                   "Chanson",
                   "Opera",
                   "Chamber Music",
                   "Sonata",
                   "Symphony",
                   "Booty Bass",
                   "Primus",
                   "Porn Groove",
                   "Satire",
                   "Slow Jam",
                   "Club",
                   "Tango",
                   "Samba",
                   "Folklore",
                   "Ballad",
                   "Power Ballad",
                   "Rhytmic Soul",
                   "Freestyle",
                   "Duet",
                   "Punk Rock",
                   "Drum Solo",
                   "Acapella",
                   "Euro-House",
                   "Dance Hall",
                   "Goa",
                   "Drum & Bass",
                   "Club-House",
                   "Hardcore",
                   "Terror",
                   "Indie",
                   "Brit Pop",
                   "Neger punk",
                   "Polsk Punk",
                   "Beat",
                   "Christian GangstaRap",
                   "Heavy Metal",
                   "Black Metal",
                   "Crossover",
                   "Contemporary Christian",
                   "ChristianRock",
                   "Merengue",
                   "Salsa",
                   "Trash Metal",
                   "Anime",
                   "JPop",
                   "Synthpop"
                  };
#endif // ID3V1TAGSDEF_H
